# EMBED API TEST

GET http://127.0.0.1:8000/chat
Accept: application/json

###

GET http://127.0.0.1:8000/embed
Accept: application/json

### EMBEDING API - AI EMBED RESULT
POST http://127.0.0.1:8000/embed
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="embed_test_file_1.pdf"

< ./test/embed_test_file_1.pdf

--boundary--