# Test your FastAPI endpoints

### MAIN API - API DESCRIPTION
GET http://127.0.0.1:8000/
Accept: application/json


### CHAT API - AI CHAT RESULT
POST http://127.0.0.1:8000/chat
Accept: application/json
Content-Type: application/json

{
"uid": "user id",
"content": "hello, world!"
}

### EMBEDING API - AI EMBED RESULT
POST http://127.0.0.1:8000/embed
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="embed_test_file_1.pdf"

< ./test/embed_test_file_1.pdf

--boundary--